### ISSUE TITLE
Test data is added twice when server is run

### ISSUE THREAD

**Issue by petak5** [ProgrammingBuddies/programmingbuddies-api#31]
**Description:** when I populate database with test data, it get's added twice per run without `--reset-db` flag. With `--reset-db` it wipes DB contents and adds test data once as expected.

**How to reporcude:**
- checkout `entities` branch
- uncomment test data in `api.models.__init__.py`
- run the server without `--reset-db`
- test data will be added to DB twice, which is incorrect

**Comment by ghost** [comment]
this seems to be a 'feature' of flasks dev mode.
It seems to restart the app immediately after loading, leading to all the __init__.py files being executed twice.
this also happens with the reset flag but in that case the database is reset every time so you only see the test data being added once

remove the line `FLASK_ENV=development` from the .env file and you'll see that even without the reset flag, there is only one row added
