### ISSUE TITLE
Does a spec sheet exist for this project?

### ISSUE THREAD

**Issue by archae0pteryx** [ProgrammingBuddies/programmingbuddies-api#47]
Do we have a spec sheet? If it's only been talked about in discord can we compile the notes into an actual spec sheet?

**Comment by petak5** [comment]
We have 4 project boards regarding this plus the 5th is the Kanban board, you can check it out [here](https://github.com/ProgrammingBuddies/programmingbuddies-api/projects).
It might be chaotic and little bit outdated but that's all we used to plan out the necessary functionality.

**Comment by petak5** [comment]
I have closed those outdated and not very descriptive boards.

Instead of that we've compiled a short list of goals and features and I've rewritten them into a wiki in the ui repository: https://github.com/ProgrammingBuddies/programmingbuddies-ui/wiki
