### ISSUE TITLE
Authentication not working?

### ISSUE THREAD

**Issue by petak5** [ProgrammingBuddies/programmingbuddies-api#58]

**Comment by luko0610** [comment]
Can be tested the following way:
1) Add this route:
```python
@app.route("/getcurrentuser",` methods=["GET"])
@login_required
def getCurrentUser():
    return current_user.id, 200
```

Checkout the login branch of the frontend and start it:
Then go to localhost:3000/private.
That should start the register process and execute a get request to the /getcurrentuser route after that.
You can then then see in the console that the http request gets a 401 returned.

**Comment by ghost** [comment]
a jwt token is now returned with the callback to the frontend.
TODO: 
- not as query parameter but as part of the route
- clean up backend code
- token lifetime?
- better register/login handling
- handle state
